### ISSUE TITLE
Would it be better to use a bib database format to store "paper tracking" info?

### ISSUE THREAD

**Issue by dschwilk** [SmithEcophysLab/lab_meeting#2]
`labmeeting_papertracking.csv` is structured and has a link, but one cannot recreate the reference from the info (eg no full authors listed, edition, etc) it is also a non standard format.  What about simply storing as bibtex?  Or if that is overkill, perhaps just a plain text file were we paste references in a bibliography type format and always include a link?

Just ideas. I think the structure of csv here is not really adding anything.

**Comment by SmithEcophysLab** [comment]
Agree that a plain text file would be better!

**Comment by SmithEcophysLab** [comment]
I created a markdown file for formatted citations and links. See the beginning of the file for more information.
