### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by dschwilk** [SmithEcophysLab/lab_meeting#3]
I edited the `labmeeting_papertracking.csv` file and noticed that the file was stored with windows line endings. Therefore, my 2 line edit  changed every single line and therefore made the diff pretty useless.

The standard in a multi os project is to store everything in git using linux line endings (which are also mac line endings, "LF" vs windows "CR LF").  Best plan is to make sure you have set your global line endings handling:

```bash
git config --global core.autocrlf input
```

It is also worth setting on a per-repository basis in case users have not set the global option on their local git installation. See https://help.github.com/en/articles/configuring-git-to-handle-line-endings

**Comment by dschwilk** [comment]
The problem could be using microsoft office on a mac.  At least as of a couple of years ago, MS excel on mac had a bug where it saved csv files with the wrong line endings.  This breaks git's automatic handling of line endings because git notes that commit is coming from mac os and therefore assumes that line endings are linux/mac style.  Like many long standing bugs in MS office, this may never get fixed.  One solution is to use libreoffice or a dedicated csv editor if you are on mac.

See https://nicercode.github.io/blog/2013-04-30-excel-and-line-endings/ for a description of the bug I think might have caused this and for a workaround to use in the git setup on the offending machine if you wnat to keep using ms excel.

**Comment by SmithEcophysLab** [comment]
This a good point! Thanks Dylan.

I've created a markdown file for adding journal articles to replace the csv file. I think this formatting is more user friendly.
